enum ActionType {
  LOAD_SMALL_CATEFORIES = 'LOAD_SMALL_CATEFORIES',
  AGGREGATE_SWEETS_BY_SMALL_CATEGORY_REQUEST = 'AGGREGATE_SWEETS_BY_SMALL_CATEGORY_REQUEST',
  AGGREGATE_SWEETS_BY_SMALL_CATEGORY_SUCCESS = 'AGGREGATE_SWEETS_BY_SMALL_CATEGORY_SUCCESS',
  AGGREGATE_SWEETS_BY_SMALL_CATEGORY_FAILURE = 'AGGREGATE_SWEETS_BY_SMALL_CATEGORY_FAILURE',
}

export default ActionType;
